services:
  clash:
    image: dreamacro/clash
    ports:
      - "7890:7890"
      - "7891:7891"
      - "9090:9090"
    configs:
      - clash_config:/root/.config/clash/config.yaml
    restart: always

  yacd:
    image: haishanh/yacd
    ports:
      - "7892:80"
    depends_on:
      - clash
    restart: always
