configs:
  clash_config:
    external: true

services:
  clash:
    image: dreamacro/clash
    ports:
      - "7890:7890"
      - "7891:7891"
      - "9090:9090"
    configs:
      - source:  clash_config
        target: /root/.config/clash/config.yaml

  yacd:
    image: haishanh/yacd
    ports:
      - "7892:80"
    depends_on:
      - clash