services:
  clash:
    image: dreamacro/clash
    container_name: clash
    ports:
      - "7890:7890"
      - "7891:7891"
      - "9090:9090"
    expose:
      - 9090
    environment:
      - CLASH_EXTERNAL_CONTROLLER=0.0.0.0:9090 
    restart: always

  yacd:
    image: haishanh/yacd
    container_name: yacd
    ports:
      - "7892:80"
    environment:
      - CLASH_API_URL=http://clash:9090
    depends_on:
      - clash
    restart: always