services:
  clash:
    image: dreamacro/clash
    container_name: clash
    ports:
      - "7890:7890"
      - "7891:7891"
    restart: always

  yacd:
    image: haishanh/yacd
    container_name: yacd
    ports:
      - "7892:80"
    environment:
      - CLASH_API_URL=http://clash:9090
    depends_on:
      - clash
    restart: always