---
services:
  s-ui:
    image: alireza7/s-ui
    container_name: s-ui
    hostname: "s-ui"
    volumes:
      - "singbox-db:/app/db"
      - "singbox-cert:/app/cert"
    tty: true
    restart: unless-stopped
    ports:
      - "2095:2095"
      - "2096:2096"
    networks:
      - s-ui
    entrypoint: "./entrypoint.sh"

volumes:
  singbox-db:
    driver: local
  singbox-cert:
    driver: local

networks:
  s-ui:
    driver: bridge
